import { ContentTemplate, ContentType } from '../types';

export const listTemplate: ContentTemplate = {
  type: ContentType.LIST,
  template: `{{commandDescriptions}}`,
  requiredVariables: ['commandDescriptions']
};

export interface CommandDescription {
  command: string;
  description: string;
}

export const formatCommandDescriptions = (commands: CommandDescription[]): string => {
  return commands
    .map(({ command, description }) => `- ${command}\n${description}`)
    .join('\n\n');
};

export const defaultCommandDescriptions: CommandDescription[] = [
  { command: '3d', description: 'Cat text effect' },
  { command: 'add', description: 'add a member to groups' },
  { command: 'afk', description: 'Set AFK (Away From Keyboard) status' },
  { command: 'alive', description: 'Display the bot\'s alive status message with optional custom text.' },
  { command: 'allvar', description: 'Display all stored variables in sorted order.' },
  { command: 'amute', description: 'Schedule automatic group muting at a specified time with an optional custom message.' },
  { command: 'angel', description: 'text effect' },
  { command: 'antifake', description: 'Enable or configure anti-fake number' },
  { command: 'antigm', description: 'Manage anti group mention configuration' },
  { command: 'antilink', description: 'Enable or configure anti-link' },
  { command: 'antispam', description: 'Enable or disable the AntiSpam feature for the group.' },
  { command: 'antiword', description: 'Filter specific words in the group chat' },
  { command: 'apk', description: 'Download APK from APKMirror' },
  { command: 'aunmute', description: 'Schedule automatic group unmuting at a specified time with an optional custom message.' },
  { command: 'avec', description: 'Convert an audio clip into a video.' },
  { command: 'avenger', description: 'text effect' },
  { command: 'avm', description: 'Merge audio and video files into one.' },
  { command: 'bass', description: 'Alter the bass levels of an audio file.' },
  { command: 'bing', description: 'bing ai' },
  { command: 'black', description: 'Convert an audio clip into a video with a black background.' },
  { command: 'block', description: 'Blocks the specified user.' },
  { command: 'bloody', description: 'bloody Look Photo editor.' },
  { command: 'blown', description: 'audio mod' },
  { command: 'blub', description: 'text effect' },
  { command: 'bokeh', description: 'bokeh Photo editor.' },
  { command: 'bpink', description: 'Cat text effect' },
  { command: 'calc', description: 'calculator' },
  { command: 'call', description: 'Automatically reject incoming calls.' },
  { command: 'caption', description: 'copy or add caption to video or image' },
  { command: 'cartoon', description: 'Dramatic Look Photo editor.' },
  { command: 'cat', description: 'Cat text effect' },
  { command: 'circle', description: 'Convert an image into a circular sticker.' },
  { command: 'clear', description: 'delete whatsapp chat' },
  { command: 'color', description: 'color Photo editor.' },
  { command: 'common', description: 'Show or kick common memebers in two or more groups' },
  { command: 'compress', description: 'Compress a video file to reduce its size.' },
  { command: 'contacts', description: 'contact manager' },
  { command: 'crop', description: 'Crop a video to the specified dimensions.' },
  { command: 'cut', description: 'Cut a segment from an audio or video file.' },
  { command: 'dall', description: 'dall image generator' },
  { command: 'dark', description: 'Dramatic Look Photo editor.' },
  { command: 'deep', description: 'audio mod' },
  { command: 'delBudget', description: 'to delete income | expense' },
  { command: 'delcmd', description: 'to del cmd' },
  { command: 'delete', description: 'Anti-delete: Recover deleted messages' },
  { command: 'delgreet', description: 'Delete the personalized greeting message' },
  { command: 'delschedule', description: 'Delete a scheduled message by specifying the target JID and time, or remove all scheduled messages.' },
  { command: 'delsudo', description: 'remove replied or mentioned or given num to sudo' },
  { command: 'delvar', description: 'Delete a variable by specifying its key.' },
  { command: 'demon', description: 'demon Look Photo editor.' },
  { command: 'demote', description: 'Remove admin role' },
  { command: 'dlt', description: 'delete replied messages' },
  { command: 'doc', description: 'media to doc msg' },
  { command: 'earrape', description: 'audio mod' },
  { command: 'emix', description: 'mix emojis' },
  { command: 'emoji', description: 'emojis' },
  { command: 'enhance', description: 'horned Look Photo editor.' },
  { command: 'exif', description: 'Extract Exif metadata from a sticker' },
  { command: 'expense', description: 'to set expense' },
  { command: 'fancy', description: 'Creates fancy text from given text' },
  { command: 'fast', description: 'audio mod' },
  { command: 'fat', description: 'audio mod' },
  { command: 'fb', description: 'Download Facebook video' },
  { command: 'filter', description: 'Manage filters in groups' },
  { command: 'find', description: 'Find the Song' },
  { command: 'forward', description: 'Forward replied message to specified JID(s)' },
  { command: 'fullpp', description: 'Set full-size profile picture.' },
  { command: 'fullss', description: 'Take web page screenshot' },
  { command: 'gandm', description: 'Dramatic Look Photo editor.' },
  { command: 'gemini', description: 'Google Gemini AI - Ask anything!' },
  { command: 'getcmd', description: 'to get cmd' },
  { command: 'getgreet', description: 'Retrieve the personalized greeting message' },
  { command: 'getschedule', description: 'Retrieve all scheduled messages for the specified chat.' },
  { command: 'getsudo', description: 'show sudos' },
  { command: 'getvar', description: 'Display the value of a variable. Provide the variable key (case-insensitive) to retrieve its value.' },
  { command: 'gfilter', description: 'Manage global filters in groups' },
  { command: 'ginfo', description: 'Shows group invite link info' },
  { command: 'gjid', description: 'Lists all group JIDs along with their group names.' },
  { command: 'glitch', description: 'text effect' },
  { command: 'glitter', description: 'text effect' },
  { command: 'goodbye', description: 'Send a goodbye message to members' },
  { command: 'gpp', description: 'change group icon' },
  { command: 'gpt', description: 'ChatGPT fun' },
  { command: 'graffiti', description: 'text effect' },
  { command: 'groq', description: 'Interact with GROQ AI' },
  { command: 'gstop', description: 'Delete gfilters in all groups' },
  { command: 'hacker', description: 'Hacker text effect' },
  { command: 'histo', description: 'Convert audio to a visual video histogram.' },
  { command: 'horned', description: 'horned Look Photo editor.' },
  { command: 'ig', description: 'Insta Profile Search' },
  { command: 'img', description: 'Download img from google' },
  { command: 'inactive', description: 'Identify or remove inactive members based on message count or inactivity duration. Append \'kick\' to remove members.' },
  { command: 'income', description: 'to set income' },
  { command: 'insta', description: 'Download Instagram posts, reels, and videos.' },
  { command: 'invite', description: 'Get a group invite link' },
  { command: 'ison', description: 'Check if a phone number is registered on WhatsApp.' },
  { command: 'jean', description: 'simple google search' },
  { command: 'jid', description: 'Returns the JID of a user or chat. It checks for a mentioned user, a reply message, or defaults to the current chat\'s JID.' },
  { command: 'join', description: 'Join groups with invite link' },
  { command: 'kick', description: 'Remove members from Group.' },
  { command: 'kiss', description: 'kiss Photo editor.' },
  { command: 'left', description: '' },
  { command: 'light', description: 'text effect' },
  { command: 'look', description: 'Dramatic Look Photo editor.' },
  { command: 'low', description: 'Alter the audio pitch to a lower tone.' },
  { command: 'lydia', description: 'to on off chat bot' },
  { command: 'makeup', description: 'Dramatic Look Photo editor.' },
  { command: 'marvel', description: 'text effect' },
  { command: 'mediafire', description: 'Download mediafire file' },
  { command: 'mention', description: 'Configure and manage the mention feature for automated replies.' },
  { command: 'merge', description: 'Merge multiple videos into one.' },
  { command: 'mforward', description: 'forward replied msg' },
  { command: 'movie', description: 'Fetch detailed movie information, including the full plot, from the OMDB API.' },
  { command: 'mp3', description: 'Convert a video to audio or an audio clip to a voice note.' },
  { command: 'mp4', description: 'Convert an animated sticker (WebP) into an MP4 video.' },
  { command: 'msgs', description: 'Display the group\'s message count for each member, including individual totals and last seen duration.' },
  { command: 'mute', description: 'Makes groups admins only' },
  { command: 'neon', description: 'text effect' },
  { command: 'news', description: 'malayalam news' },
  { command: 'nightcore', description: 'audio mod' },
  { command: 'online', description: 'Keep your account status always online.' },
  { command: 'ope', description: 'Deletes or unsets the specified allowed commands.' },
  { command: 'page', description: 'Add an image as a page to a PDF document.' },
  { command: 'pdf', description: 'Convert images to a PDF document.' },
  { command: 'pdm', description: 'Enable or disable automatic notifications for promote/demote events in the group.' },
  { command: 'pencil', description: 'pencil Photo editor.' },
  { command: 'pfilter', description: 'Manage global filters in personal chats' },
  { command: 'photo', description: 'Convert a sticker into an image.' },
  { command: 'ping', description: 'Check the bot\'s response time (latency).' },
  { command: 'pinterest', description: 'Download Pinterest videos or images.' },
  { command: 'pitch', description: 'Adjust the pitch of an audio file.' },
  { command: 'play', description: 'Download youtube audio' },
  { command: 'plugin', description: 'Install external plugins by providing a Gist URL containing the plugin code, or list all installed plugins.' },
  { command: 'poll', description: 'poll' },
  { command: 'pp', description: 'Updates your profile picture using the image from the replied message.' },
  { command: 'promote', description: 'Give admin role' },
  { command: 'pstop', description: 'Delete pfilter in all groups' },
  { command: 'qr', description: 'Generate a QR code from the provided text or decode a QR code from a replied image.' },
  { command: 'react', description: 'React to msg' },
  { command: 'read', description: 'Enable or disable auto-reading of incoming messages.' },
  { command: 'reboot', description: 'Restart the bot instance using PM2.' },
  { command: 'reddit', description: 'Downloads a video from the specified Reddit post using the provided URL.' },
  { command: 'remove', description: 'Delete external plugins by specifying the plugin name or remove all installed plugins.' },
  { command: 'reset', description: 'Reset the message count for either the entire group or a specific member.' },
  { command: 'reverse', description: 'Reverse the playback of a video or audio clip.' },
  { command: 'revoke', description: 'Revoke Group invite link' },
  { command: 'rmbg', description: 'Removes the background from the replied image using the remove.bg API' },
  { command: 'robot', description: 'audio mod' },
  { command: 'rotate', description: 'Rotate a video to the right, left, or flip it.' },
  { command: 'save', description: 'Forward replied message to yourself' },
  { command: 'sci', description: 'text effect' },
  { command: 'scstatus', description: 'Schedule a WhatsApp status to be sent at a specified time. Use \'contact\' for imported contacts or provide specific JIDs.' },
  { command: 'setcmd', description: 'to set cmd' },
  { command: 'setgreet', description: 'Set a personalized greeting message' },
  { command: 'setschedule', description: 'Schedule a message to be sent automatically at a specified time. Provide the target JID(s) and time (in minutes-hour-day-month format; day and month are optional). Reply to the message you want to schedule.' },
  { command: 'setstatus', description: 'Set a WhatsApp status for specific contacts or for imported contacts. Reply to a message (text, image, or video) to set the status.' },
  { command: 'setsudo', description: 'add replied or mentioned or given num to sudo' },
  { command: 'setvar', description: 'Set a variable with a specific key and value. Use \'=\' to separate the key from the value.' },
  { command: 'sign', description: 'text effect' },
  { command: 'sketch', description: 'Sketch Photo editor.' },
  { command: 'skull', description: 'Skull Photo editor.' },
  { command: 'slow', description: 'audio mod' },
  { command: 'smooth', description: 'audio mod' },
  { command: 'song', description: 'Download a song from YouTube. If a URL is provided, the song is downloaded directly; otherwise, a search is performed and a list of results is generated for selection.' },
  { command: 'spotify', description: 'download track or playlist' },
  { command: 'ss', description: 'Take web page screenshot' },
  { command: 'status', description: 'Automatically manage the viewing of WhatsApp statuses.' },
  { command: 'sticker', description: 'Convert an image or video to a sticker. Reply to an image or video message to generate a sticker.' },
  { command: 'stop', description: 'Delete filters in chat' },
  { command: 'story', description: 'Download Instagram stories for the specified username. If multiple stories are available, a list will be provided for selection.' },
  { command: 'summary', description: 'to get summary of budget' },
  { command: 'tag', description: 'Tag members in the group based on your choice. Use \'all\' to mention every member, \'admin\' to mention only group admins, \'notadmin\' to mention non-admin members, or provide a custom message to be sent along with the mentions.' },
  { command: 'take', description: 'Change the sticker pack by updating its metadata. If replying to a sticker, update its pack metadata. If replying to audio, add metadata (title, artists, URL) to the file.' },
  { command: 'tattoo', description: 'text effect' },
  { command: 'tg', description: 'download telegram sticker' },
  { command: 'tictactoe', description: 'Play a TicTacToe game against an opponent. Challenge a user by mentioning them, replying to their message, or specifying their JID. Use \'tictactoe end\' to finish the game and \'tictactoe restart <opponent_jid>\' to restart with a new opponent.' },
  { command: 'tiktok', description: 'Download a TikTok video from the provided URL.' },
  { command: 'time', description: 'find time by timeZone or name or shortcode' },
  { command: 'tog', description: 'Enable or disable a bot command.' },
  { command: 'treble', description: 'Alter the treble levels of an audio file.' },
  { command: 'trim', description: 'Trim a video between specified start and duration times.' },
  { command: 'trt', description: 'Translate text using Google Translate. Specify the target language code (and optionally the source language code) when replying to a message.' },
  { command: 'tts', description: 'text to speach' },
  { command: 'tupai', description: 'audio mod' },
  { command: 'twitter', description: 'Download a Twitter video. If multiple quality options are available, you\'ll be prompted to choose one.' },
  { command: 'unblock', description: 'Unblocks the specified user.' },
  { command: 'unmute', description: 'Makes Group All participants can send Message' },
  { command: 'update', description: 'Check for new updates. Displays available updates or confirms that the bot is up-to-date.' },
  { command: 'update now', description: 'Update the bot to the latest version.' },
  { command: 'upload', description: 'Download media from a provided URL. For shortened Google Images URLs, the direct image URL is retrieved automatically.' },
  { command: 'upscale', description: 'improve image quality' },
  { command: 'url', description: 'Convert an image or video to a URL. Optionally, specify a parameter (e.g., \'imgur\') to get the URL from a specific service.' },
  { command: 'vector', description: 'Convert audio to a vector visualization video.' },
  { command: 'video', description: 'Download a YouTube video. If a direct URL is provided, the video is downloaded; if a search query is provided, a list of results is generated for selection.' },
  { command: 'vote', description: 'Initiate a vote in a WhatsApp group.' },
  { command: 'vv', description: 'antiViewOnce' },
  { command: 'wanted', description: 'Wanted Photo editor.' },
  { command: 'warn', description: 'Warn a user in the group chat. This command increases a user\'s warning count. If the count exceeds the limit, the user will be kicked from the group. Use \'warn reset\' to clear a user\'s warnings.' },
  { command: 'watercolor', description: 'Cat text effect' },
  { command: 'wcg', description: 'Word Chain Game: Participate by providing a word that continues the chain. Use \'wcg start\' to force start a new game or \'wcg end\' to stop the current game.' },
  { command: 'weather', description: 'weather info' },
  { command: 'welcome', description: 'Send a welcome message to new members' },
  { command: 'whois', description: 'Displays the profile picture and additional information (e.g., about, status) of a user or group.' },
  { command: 'wrg', description: 'Random Word Game: Engage in a game where you submit words in response to a random prompt. Use \'wrg start\' to begin a new game or \'wrg end\' to finish the game.' },
  { command: 'yami', description: 'Displays the list of commands that are currently allowed in this chat.' },
  { command: 'yta', description: 'Download YouTube audio' },
  { command: 'yts', description: 'Search for YouTube videos by query or URL. If a valid YouTube URL is provided, detailed information for the first video is returned.' },
  { command: 'ytv', description: 'Download YouTube video' },
  { command: 'zombie', description: 'zombie Look Photo editor.' },
  { command: 'zushi', description: 'Allows you to enable specific commands for use by others in the chat.' }
];
